name: test project distribution
#this is for QA auto test build,  more info here: https://docs.testproject.io/tips-and-tricks/extending-testproject-recorder-capabilities-for-dedicated-elements

on:
  push

env:
  CI: true

jobs:
  testProjectDistribution:
    name: Test Project Distribution
    runs-on: ubuntu-latest
    steps:
      - run: |
        a=`which jq`
        echo "###### $a"